### ISSUE TITLE
StreamLink DASH Timeouts

### ISSUE THREAD

**Issue by billdeitrick** [billdeitrick/pyrestreamer#2]
StreamLink doesn't seem to handle HTTP timeouts cleanly. Defaults to a 20 second timeout for segments, and crashes if that isn't met.

It looks like this is controlled by [HTTP Timeout](https://streamlink.github.io/cli.html#cmdoption-http-timeout).

Can we make StreamLink handle this in a better way? Or try increasing the timeout?

```
Unexpected output from ffmpeg proc: Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
response.begin()
File "/usr/lib/python3.7/http/client.py", line 306, in begin
File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
File "/usr/lib/python3.7/socket.py", line 589, in readinto
return self._sock.recv_into(b)
File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
return self.read(nbytes, buffer)
File "/usr/lib/python3.7/ssl.py", line 911, in read
return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
raise value
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='redactedhost.com', port=443): Read timed out. (read timeout=20.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/streamlink/plugin/api/http_session.py", line 164, in request
*args, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='redactedhost.com', port=443): Read timed out. (read timeout=20.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3/dist-packages/streamlink/stream/segmented.py", line 59, in run
for segment in self.iter_segments():
File "/usr/lib/python3/dist-packages/streamlink/stream/dash.py", line 97, in iter_segments
if not self.reload():
File "/usr/lib/python3/dist-packages/streamlink/stream/dash.py", line 111, in reload
res = self.session.http.get(self.mpd.url, exception=StreamError)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/usr/lib/python3/dist-packages/streamlink/plugin/api/http_session.py", line 175, in request
raise err
streamlink.exceptions.StreamError: Unable to open URL: https://redactedhost.com/here/Manifest.mpd (HTTPSConnectionPool(host='redactedhost.com', port=443): Read timed out. (read timeout=20.0))

[stream.ffmpegmux][error] Pipe copy aborted: /tmp/ffmpeg-9-918
```

**Comment by billdeitrick** [comment]
https://github.com/streamlink/streamlink/issues/1146

**Comment by billdeitrick** [comment]
Looks like StreamLink wasn't quite working as advertised by the docs. Basically, we weren't getting any retries on the manifest file. So, one timed out request and that was it...

Forked StreamLink and fixed this here: https://github.com/billdeitrick/streamlink/tree/dash-args

Using this fork in the Docker image for now. In the future, need to see about creating a PR for this change (will leave this open until PR is created).
